"""
Travel experience catalog for Meridian demo — 30 packages across 6 categories.
Used by seed_data.py (products table schema unchanged; rows are trips).
"""

def _img(photo_id: str) -> str:
    return f"https://images.unsplash.com/photo-{photo_id}?auto=format&fit=crop&w=800&h=600&q=80"

TRAVEL_PRODUCTS = [
    # City Breaks
    {"product_id": "CTY-001", "name": "Paris Long Weekend", "category": "City Breaks", "price": 1899.0, "brand": "Air France Vacations",
     "description": "Four nights in Le Marais with Louvre tickets, Seine dinner cruise, and Montmartre food walk. Spring and fall departures.",
     "image_url": _img("1502602898657-3e91760cbb34"),
     "available_sizes": ["3 nights", "4 nights", "5 nights"], "inventory": {"3 nights": 8, "4 nights": 12, "5 nights": 6}},
    {"product_id": "CTY-002", "name": "Tokyo Culture & Cuisine", "category": "City Breaks", "price": 2499.0, "brand": "ANA Holidays",
     "description": "Shibuya base, Tsukiji breakfast tour, teamLab, and day trip to Hakone. Rail pass included.",
     "image_url": _img("1540959733332-eab4deabeeaf"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 10, "7 nights": 7}},
    {"product_id": "CTY-003", "name": "New York City Explorer", "category": "City Breaks", "price": 1699.0, "brand": "Delta Vacations",
     "description": "Midtown hotel, Broadway show credit, High Line walk, and Brooklyn day pass.",
     "image_url": _img("1496442226666-8d4d0e62e6e9"),
     "available_sizes": ["3 nights", "4 nights"], "inventory": {"3 nights": 15, "4 nights": 9}},
    {"product_id": "CTY-004", "name": "Barcelona Architecture Week", "category": "City Breaks", "price": 1599.0, "brand": "Iberia Escapes",
     "description": "Gothic Quarter boutique stay, Sagrada Família skip-the-line, tapas tour, and Costa Brava optional day.",
     "image_url": _img("1539037116277-4245f8591aa1"),
     "available_sizes": ["4 nights", "6 nights"], "inventory": {"4 nights": 11, "6 nights": 5}},
    {"product_id": "CTY-005", "name": "Rome Ancient & Modern", "category": "City Breaks", "price": 1749.0, "brand": "Alitalia Tours",
     "description": "Colosseum and Vatican small-group tours, Trastevere evenings, and Tuscan wine day trip.",
     "image_url": _img("1552832230-c0197dd311b5"),
     "available_sizes": ["4 nights", "5 nights"], "inventory": {"4 nights": 8, "5 nights": 6}},
    # Beach & Resort
    {"product_id": "BCH-001", "name": "Maldives Overwater Villa", "category": "Beach & Resort", "price": 4299.0, "brand": "Emirates Holidays",
     "description": "Five nights overwater bungalow, seaplane transfer, snorkeling, and sunset dolphin cruise.",
     "image_url": _img("1514282401047-d79a71a590e8"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 4, "7 nights": 3}},
    {"product_id": "BCH-002", "name": "Cancún All-Inclusive Escape", "category": "Beach & Resort", "price": 2199.0, "brand": "Sunwing",
     "description": "Beachfront resort, meals and drinks included, Chichen Itza excursion optional.",
     "image_url": _img("1507525428034-b723cf961d3e"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 20, "7 nights": 14}},
    {"product_id": "BCH-003", "name": "Bali Rice Terrace Retreat", "category": "Beach & Resort", "price": 1899.0, "brand": "Garuda Getaways",
     "description": "Ubud villa, yoga mornings, temple tour, and Seminyak beach club day.",
     "image_url": _img("1537996194471-f6576d1ded6a"),
     "available_sizes": ["6 nights", "8 nights"], "inventory": {"6 nights": 9, "8 nights": 6}},
    {"product_id": "BCH-004", "name": "Santorini Caldera Views", "category": "Beach & Resort", "price": 2799.0, "brand": "Aegean Blue",
     "description": "Cave suite in Oia, catamaran sunset sail, and winery tasting in volcanic soil.",
     "image_url": _img("1613395877344-13d4a8e0d49e"),
     "available_sizes": ["4 nights", "6 nights"], "inventory": {"4 nights": 7, "6 nights": 4}},
    {"product_id": "BCH-005", "name": "Hawaiian Island Hopper", "category": "Beach & Resort", "price": 3199.0, "brand": "Hawaiian Airlines",
     "description": "Oahu and Maui split stay, luau, Pearl Harbor tour, and Road to Hana drive day.",
     "image_url": _img("1542259009477-d625fcaaed79"),
     "available_sizes": ["7 nights", "10 nights"], "inventory": {"7 nights": 8, "10 nights": 5}},
    # Adventure & Outdoors
    {"product_id": "ADV-001", "name": "Patagonia Trek Expedition", "category": "Adventure & Outdoors", "price": 3899.0, "brand": "REI Adventures",
     "description": "Guided W Trek highlights, refugio lodging, gear list provided. Moderate fitness required.",
     "image_url": _img("1516026672322-bc52d61a55d5"),
     "available_sizes": ["8 nights", "10 nights"], "inventory": {"8 nights": 6, "10 nights": 4}},
    {"product_id": "ADV-002", "name": "Iceland Ring Road", "category": "Adventure & Outdoors", "price": 2799.0, "brand": "Nordic Trails",
     "description": "4x4 camper or guided mini-bus, glacier hike, Blue Lagoon, and northern lights chase season.",
     "image_url": _img("1483342387746-4c8b0e99ec32"),
     "available_sizes": ["6 nights", "8 nights"], "inventory": {"6 nights": 10, "8 nights": 7}},
    {"product_id": "ADV-003", "name": "Costa Rica Rainforest & Zip", "category": "Adventure & Outdoors", "price": 2199.0, "brand": "EcoVenture",
     "description": "Arenal volcano lodge, canopy zip lines, wildlife night walk, and Pacific beach finale.",
     "image_url": _img("1519005039724-4f74e549e194"),
     "available_sizes": ["7 nights", "9 nights"], "inventory": {"7 nights": 12, "9 nights": 8}},
    {"product_id": "ADV-004", "name": "New Zealand South Island", "category": "Adventure & Outdoors", "price": 3599.0, "brand": "Air New Zealand",
     "description": "Queenstown adrenaline, Milford Sound cruise, and Franz Josef glacier heli-hike option.",
     "image_url": _img("1469521664190-425a0b0c3cda"),
     "available_sizes": ["10 nights", "12 nights"], "inventory": {"10 nights": 5, "12 nights": 3}},
    {"product_id": "ADV-005", "name": "Nepal Everest Base Camp Trek", "category": "Adventure & Outdoors", "price": 3299.0, "brand": "Himalaya Guides",
     "description": "Teahouse trek with acclimatization days, permits included. High altitude — preparation guide sent.",
     "image_url": _img("1544735716-392fe2489ffa"),
     "available_sizes": ["14 nights"], "inventory": {"14 nights": 4}},
    # Wellness & Luxury
    {"product_id": "WEL-001", "name": "Swiss Alps Spa Retreat", "category": "Wellness & Luxury", "price": 4499.0, "brand": "Swissôtel",
     "description": "Alpine thermal spa, daily treatments, mountain air hikes, and gourmet half-board.",
     "image_url": _img("1519681393784-d120267933ba"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 6, "7 nights": 4}},
    {"product_id": "WEL-002", "name": "Amalfi Coast Villa Week", "category": "Wellness & Luxury", "price": 3999.0, "brand": "Belmond",
     "description": "Cliffside villa, private boat day, Positano dining, and Ravello concert evening.",
     "image_url": _img("1534113414509-0bd4c19e7048"),
     "available_sizes": ["6 nights", "8 nights"], "inventory": {"6 nights": 3, "8 nights": 2}},
    {"product_id": "WEL-003", "name": "Dubai Luxury Stopover", "category": "Wellness & Luxury", "price": 2899.0, "brand": "Emirates",
     "description": "Burj view suite, desert safari, spa day, and fine dining credit at DIFC.",
     "image_url": _img("1518684079-3c830dcef090"),
     "available_sizes": ["3 nights", "5 nights"], "inventory": {"3 nights": 14, "5 nights": 9}},
    {"product_id": "WEL-004", "name": "Kyoto Ryokan & Onsen", "category": "Wellness & Luxury", "price": 3299.0, "brand": "JAL Packages",
     "description": "Traditional ryokan, kaiseki dinners, tea ceremony, and bamboo forest morning walk.",
     "image_url": _img("1493976040374-85c8e5778f71"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 7, "7 nights": 5}},
    {"product_id": "WEL-005", "name": "Tuscany Wine & Wellness", "category": "Wellness & Luxury", "price": 3699.0, "brand": "Trafalgar",
     "description": "Villa stay, vineyard tours, cooking class, and truffle season optional add-on.",
     "image_url": _img("1523531294919-4bcd7c65e216"),
     "available_sizes": ["6 nights", "8 nights"], "inventory": {"6 nights": 5, "8 nights": 3}},
    # Family Trips
    {"product_id": "FAM-001", "name": "Orlando Theme Park Week", "category": "Family Trips", "price": 2499.0, "brand": "Disney Travel",
     "description": "Resort hotel, multi-park tickets, character breakfast, and pool days built in.",
     "image_url": _img("1568605114967-a37c8dd9d91a"),
     "available_sizes": ["5 nights", "7 nights"], "inventory": {"5 nights": 18, "7 nights": 12}},
    {"product_id": "FAM-002", "name": "Yellowstone Wildlife Safari", "category": "Family Trips", "price": 2799.0, "brand": "National Park Tours",
     "description": "Lodge near park gate, guided wildlife drives, junior ranger program, and geysers day.",
     "image_url": _img("1478135233761-d627c60eb9c2"),
     "available_sizes": ["6 nights", "8 nights"], "inventory": {"6 nights": 8, "8 nights": 5}},
    {"product_id": "FAM-003", "name": "Mediterranean Family Cruise", "category": "Family Trips", "price": 3199.0, "brand": "Royal Caribbean",
     "description": "Balcony cabin, kids club, Rome and Barcelona ports, and all-inclusive shipboard dining.",
     "image_url": _img("1566073771259-6a8506099945"),
     "available_sizes": ["7 nights"], "inventory": {"7 nights": 22}},
    {"product_id": "FAM-004", "name": "Costa del Sol Beach Club", "category": "Family Trips", "price": 1999.0, "brand": "TUI Family",
     "description": "Family suite, kids pool, beach access, and optional water park passes.",
     "image_url": _img("1473496163314-42ba249543ec"),
     "available_sizes": ["7 nights", "10 nights"], "inventory": {"7 nights": 16, "10 nights": 10}},
    {"product_id": "FAM-005", "name": "London & Harry Potter Studio", "category": "Family Trips", "price": 2299.0, "brand": "British Airways",
     "description": "Central London stay, studio tour tickets, Thames river cruise, and museum day.",
     "image_url": _img("1513635269975-59663e0ac1ad"),
     "available_sizes": ["5 nights", "6 nights"], "inventory": {"5 nights": 11, "6 nights": 7}},
    # Business Travel
    {"product_id": "BIZ-001", "name": "London Executive Quick Trip", "category": "Business Travel", "price": 1499.0, "brand": "British Airways",
     "description": "City airport hotel, lounge access, express train credit, and flexible change policy.",
     "image_url": _img("1529655687286-ab3457b0123a"),
     "available_sizes": ["2 nights", "3 nights"], "inventory": {"2 nights": 25, "3 nights": 18}},
    {"product_id": "BIZ-002", "name": "Singapore Hub Stopover", "category": "Business Travel", "price": 1299.0, "brand": "Singapore Airlines",
     "description": "Changi-area hotel, fast Wi‑Fi, meeting room credit, and Gardens by the Bay evening.",
     "image_url": _img("1525625173904-bf99e5e99460"),
     "available_sizes": ["2 nights", "3 nights"], "inventory": {"2 nights": 30, "3 nights": 20}},
    {"product_id": "BIZ-003", "name": "Dubai Conference Package", "category": "Business Travel", "price": 1899.0, "brand": "Emirates Business",
     "description": "DWC-adjacent hotel, conference shuttle, late checkout, and visa assistance.",
     "image_url": _img("1542314831-068cd1dbfeeb"),
     "available_sizes": ["3 nights", "4 nights"], "inventory": {"3 nights": 14, "4 nights": 9}},
    {"product_id": "BIZ-004", "name": "NYC Meetings Marathon", "category": "Business Travel", "price": 1699.0, "brand": "United Business",
     "description": "Midtown business hotel, car service credit, quiet-floor room, and same-day laundry.",
     "image_url": _img("1485871981521-5b1fd3805eee"),
     "available_sizes": ["3 nights", "5 nights"], "inventory": {"3 nights": 20, "5 nights": 12}},
    {"product_id": "BIZ-005", "name": "Frankfurt Trade Fair Stay", "category": "Business Travel", "price": 1399.0, "brand": "Lufthansa",
     "description": "Messe-connected hotel, fair shuttle pass, early breakfast, and rail pass to city center.",
     "image_url": _img("1467269207814-8dbca6048416"),
     "available_sizes": ["3 nights", "4 nights"], "inventory": {"3 nights": 16, "4 nights": 10}},
]
